channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5

  - pip=20.1
  - wheel=0.37.1
  # - nodejs=16.14.2

  - pip:
    - git+https://github.com/FurySwordXD/VNC.git
    # rccPostInstall:
    # - npm install node-rdpjs
